version: '3'
services:
  gobuhat-backend:
    build: .
    container_name: "gobuhat-backend"
    working_dir: /var/www
    volumes:
        - .:/var/www:rw
    links:
        - mongodb
    depends_on:
        - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - /data/db:/data/db
    ports:
        - 27017:27018