module.exports = {
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    USER_DOES_NOT_EXIST: 'USER_DOES_NOT_EXIST',
    THREAD_DOES_NOT_EXIST: 'THREAD_DOES_NOT_EXIST',
    USER_HAVE_NOT_ACCESS_TO_THREAD: 'USER_HAVE_NOT_ACCESS_TO_THREAD',
    NOT_AUTHORIZED: 'NOT_AUTHORIZED',
};